import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";
const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Doc4Life",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Toaster />
        {children}
        <Footer />
      </body>
    </html>
  );
}
